### ISSUE TITLE
What counts as "your code"?

### ISSUE THREAD

**Issue by darklegal** [roket333/Minecraft-Everything-Random-Mod#2]
Hello, this seems like a pretty cool mod you have here! Hope you succeed with your goal in this project!

However, there are a few points I would like to bring to bring up with you.

In your [README.md](https://github.com/roket333/Minecraft-Everything-Random-Mod/blob/master/README.md) file, you state that you are not fine with people using your code in their own mod.

What counts as "your code"? Does basic code, such as defining items or block, count as your code? If the code is modified, is it still your code?

Also, [consider adding a license to your repository.](https://choosealicense.com/)

**Comment by roket333** [comment]
Hello, thank you for the good wishes with the mod
what would count as my code is all of the mod's code
if the code is modified, i would consider it sill mine because i originally created it
to be honest, i don't imagine that someone would want to take *my* code of all people, so i really just put that there without thinking about it much, and will likely be changed

also, i will look into adding a license, thank you for bringing that to my attention

**Comment by roket333** [comment]
I have now added a license as well as improved the whats now called "Do's and Dont's" section, hopefully this resolves any confusion in the future
